version: '3.1'
services:
  sqldb:
    restart: always
    image: mysql
    ports:
     - 3306:3306
    volumes:
      - db-vol:/var/lib/mysql/data
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=yeeapi
    