name: Build and push image to ECR
on:
  push:
    branches: [ main ]
jobs:
  build-and-push:
    name: Build image and push it to ECR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Config AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.YEEINFRA_AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{ secrets.YEEINFRA_AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Log into ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, Tag, and Push the Image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.AWS_REPO }}
        IMAGE_TAG: 1.6
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
